# Site settings
title: Greenhouse Blog
email: team@greenhouseci.com
description: 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.greenhouseci.com" # the base hostname & protocol for your site
twitter_username: greenhouseci
github_username:  greenhouseci
disqus_shortname: greenhouseci

# Build settings
markdown: kramdown
paginate: 5
highlighter: pygments

permalink:   /:categories/:title/

excerpt_separator: <!--more-->
