# Site settings
title: Greenhouse Blog
email: team@greenhouseci.com
url: "http://blog.greenhouseci.com" # the base hostname & protocol for your site
# url: "http://127.0.0.1:4000/" # use for local testing
baseurl: "" # the subpath of your site, e.g. /blog/
twitter_username: greenhouseci
github_username:  greenhouseci
disqus_shortname: greenhouseci

# Build settings
markdown: kramdown
paginate: 5
highlighter: rouge

permalink:   /:categories/:title/

excerpt_separator: <!--more-->

gems:
   - jekyll-paginate

exclude:
    - node_modules
